"""Auto-generated by Detective — warrant-classed tests for Wesker/ci.py::profile_function_cached."""

import pytest

from Wesker.ci import profile_function_cached


@pytest.mark.detective
def test_profile_function_cached_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = profile_function_cached("abc", "abc", "abc", 2.5, 1, 2)
    assert result is None
