"""Auto-generated by Detective — warrant-classed tests for Wesker/self_profile.py::targets_own_package."""

import pytest

from Wesker.self_profile import targets_own_package


@pytest.mark.detective
def test_targets_own_package_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = targets_own_package(["Wesker/engine.py"], "Wesker", ".")
    assert result is True


@pytest.mark.detective
def test_targets_own_package_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = targets_own_package(["src/app.py"], "Wesker", ".")
    assert result is False


@pytest.mark.detective
def test_targets_own_package_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = targets_own_package(["Weskerish/x.py"], "Wesker", ".")
    assert result is False


@pytest.mark.detective
def test_targets_own_package_value_3():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = targets_own_package(["x"], "a", "")
    assert result is False


@pytest.mark.detective
def test_targets_own_package_value_4():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = targets_own_package([], "", "")
    assert result is False


@pytest.mark.detective
def test_targets_own_package_value_5():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = targets_own_package(["x"], "abc", "abc")
    assert result is True
