"""Auto-generated by Detective — warrant-classed tests for Wesker/engine.py::_unwind_dead_end."""

import pytest

from Wesker.interrupt import injection_landed as _unwind_dead_end


@pytest.mark.detective
def test__unwind_dead_end_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _unwind_dead_end(1)
    assert result is True
