"""Auto-generated by Detective — warrant-classed tests for Wesker/engine.py::_baseline_failures."""

import pytest

from Wesker.engine import _baseline_failures


@pytest.mark.detective
def test__baseline_failures_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _baseline_failures([None], 1, "abc", 2.5)
    assert result == set()


@pytest.mark.detective
def test__baseline_failures_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _baseline_failures([None], -1, "", -1.0)
    assert result == set()
