"""Auto-generated by Detective — warrant-classed tests for Wesker/engine.py::_is_private_copy."""

import pytest

from Wesker.engine import _is_private_copy


@pytest.mark.detective
def test__is_private_copy_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = _is_private_copy("abc", "abc")
    assert result is True
